articles:
  # - article-template
  - cape-cod
  - nyc-bnw
  - montreal-bnw
  - montreal-street-art
  - december-in-san-diego-2
  - december-in-san-diego-1
  - gaspe-peninsula
  # - article-one
  # - article-two
  # - article-three