articles:
  - scientific-developer
  - cape-cod
  - nyc-bnw
  - montreal-bnw
  - montreal-street-art
  - december-in-san-diego-2
  - december-in-san-diego-1
  - gaspe-peninsula
  - toronto-day-6
  - toronto-day-5
  - toronto-day-4
  - toronto-day-3
  - toronto-day-2
  - toronto-day-1
  - pole-emploi-story