articles:
  # - article-template
  - scientific-developer
  - cape-cod
  - nyc-bnw
  - montreal-bnw
  - montreal-street-art
  - december-in-san-diego-2
  - december-in-san-diego-1
  - gaspe-peninsula
  - toronto-day-5
  - pole-emploi-story
  # - article-one
  # - article-two
  # - article-three